package com.boating.cs;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Apr 16 16:18:00 CEST 2018 by fh231
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Address
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ADDRESS.<p>
     * 
     */
    public static final OWLClass CLASS_ADDRESS = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Address"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Berth
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BERTH.<p>
     * 
     */
    public static final OWLClass CLASS_BERTH = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Berth"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Boat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOAT.<p>
     * 
     */
    public static final OWLClass CLASS_BOAT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Boat"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#BoatRentalProvider
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOATRENTALPROVIDER.<p>
     * 
     */
    public static final OWLClass CLASS_BOATRENTALPROVIDER = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#BoatRentalProvider"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#CabinCruiser
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CABINCRUISER.<p>
     * 
     */
    public static final OWLClass CLASS_CABINCRUISER = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#CabinCruiser"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#CommercialBoat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMERCIALBOAT.<p>
     * 
     */
    public static final OWLClass CLASS_COMMERCIALBOAT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#CommercialBoat"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#CommercialBoatRentalProvider
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMERCIALBOATRENTALPROVIDER.<p>
     * 
     */
    public static final OWLClass CLASS_COMMERCIALBOATRENTALPROVIDER = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#CommercialBoatRentalProvider"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#CommercialRoute
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMERCIALROUTE.<p>
     * 
     */
    public static final OWLClass CLASS_COMMERCIALROUTE = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#CommercialRoute"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Contact
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTACT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTACT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Contact"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Cutter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CUTTER.<p>
     * 
     */
    public static final OWLClass CLASS_CUTTER = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Cutter"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Dinghy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DINGHY.<p>
     * 
     */
    public static final OWLClass CLASS_DINGHY = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Dinghy"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Dragon
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DRAGON.<p>
     * 
     */
    public static final OWLClass CLASS_DRAGON = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Dragon"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Email
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EMAIL.<p>
     * 
     */
    public static final OWLClass CLASS_EMAIL = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Email"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Engine
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENGINE.<p>
     * 
     */
    public static final OWLClass CLASS_ENGINE = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Engine"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Ferry
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FERRY.<p>
     * 
     */
    public static final OWLClass CLASS_FERRY = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Ferry"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Harbour
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HARBOUR.<p>
     * 
     */
    public static final OWLClass CLASS_HARBOUR = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Harbour"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Haven
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAVEN.<p>
     * 
     */
    public static final OWLClass CLASS_HAVEN = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Haven"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Hobie-Tiger
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOBIE_TIGER.<p>
     * 
     */
    public static final OWLClass CLASS_HOBIE_TIGER = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Hobie-Tiger"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Hobie-Wildcat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOBIE_WILDCAT.<p>
     * 
     */
    public static final OWLClass CLASS_HOBIE_WILDCAT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Hobie-Wildcat"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Laser
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LASER.<p>
     * 
     */
    public static final OWLClass CLASS_LASER = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Laser"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#LeisureBoatRentalProvider
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEISUREBOATRENTALPROVIDER.<p>
     * 
     */
    public static final OWLClass CLASS_LEISUREBOATRENTALPROVIDER = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#LeisureBoatRentalProvider"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#LeisureRoute
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEISUREROUTE.<p>
     * 
     */
    public static final OWLClass CLASS_LEISUREROUTE = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#LeisureRoute"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Mirror
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIRROR.<p>
     * 
     */
    public static final OWLClass CLASS_MIRROR = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Mirror"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#MotorBoat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOTORBOAT.<p>
     * 
     */
    public static final OWLClass CLASS_MOTORBOAT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#MotorBoat"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Multihull
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MULTIHULL.<p>
     * 
     */
    public static final OWLClass CLASS_MULTIHULL = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Multihull"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#NonCommercialBoat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONCOMMERCIALBOAT.<p>
     * 
     */
    public static final OWLClass CLASS_NONCOMMERCIALBOAT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#NonCommercialBoat"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Optimist
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OPTIMIST.<p>
     * 
     */
    public static final OWLClass CLASS_OPTIMIST = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Optimist"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Port
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PORT.<p>
     * 
     */
    public static final OWLClass CLASS_PORT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Port"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Route
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROUTE.<p>
     * 
     */
    public static final OWLClass CLASS_ROUTE = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Route"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#SailingBoat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SAILINGBOAT.<p>
     * 
     */
    public static final OWLClass CLASS_SAILINGBOAT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#SailingBoat"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Sloop
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SLOOP.<p>
     * 
     */
    public static final OWLClass CLASS_SLOOP = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Sloop"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Telephone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TELEPHONE.<p>
     * 
     */
    public static final OWLClass CLASS_TELEPHONE = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Telephone"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Topcat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TOPCAT.<p>
     * 
     */
    public static final OWLClass CLASS_TOPCAT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Topcat"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Tornado
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TORNADO.<p>
     * 
     */
    public static final OWLClass CLASS_TORNADO = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Tornado"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Trawler
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRAWLER.<p>
     * 
     */
    public static final OWLClass CLASS_TRAWLER = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Trawler"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Tug
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TUG.<p>
     * 
     */
    public static final OWLClass CLASS_TUG = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Tug"));

    /* ***************************************************
     * Class http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Yacht
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class YACHT.<p>
     * 
     */
    public static final OWLClass CLASS_YACHT = factory.getOWLClass(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#Yacht"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#acceptsBoatType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ACCEPTSBOATTYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ACCEPTSBOATTYPE = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#acceptsBoatType"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#allowedBoatType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ALLOWEDBOATTYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ALLOWEDBOATTYPE = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#allowedBoatType"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#belongsTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BELONGSTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BELONGSTO = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#belongsTo"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#boatType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BOATTYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BOATTYPE = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#boatType"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#connectsTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONNECTSTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONNECTSTO = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#connectsTo"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#contact
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTACT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTACT = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#contact"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#engine
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ENGINE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ENGINE = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#engine"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#havenBerths
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAVENBERTHS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAVENBERTHS = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#havenBerths"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#isBiggerThan
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISBIGGERTHAN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISBIGGERTHAN = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#isBiggerThan"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#isCommercial
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCOMMERCIAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCOMMERCIAL = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#isCommercial"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#isLeisure
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISLEISURE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISLEISURE = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#isLeisure"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#locatedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LOCATEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LOCATEDIN = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#locatedIn"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#motors
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MOTORS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MOTORS = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#motors"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#rentalProviderBoats
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RENTALPROVIDERBOATS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RENTALPROVIDERBOATS = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#rentalProviderBoats"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#rentalProviderHomeHaven
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RENTALPROVIDERHOMEHAVEN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RENTALPROVIDERHOMEHAVEN = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#rentalProviderHomeHaven"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#rents
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RENTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RENTS = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#rents"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#routeHavens
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ROUTEHAVENS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ROUTEHAVENS = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#routeHavens"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#routeType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ROUTETYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ROUTETYPE = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#routeType"));

    /* ***************************************************
     * Object Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#sails
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SAILS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SAILS = factory.getOWLObjectProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#sails"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#berthCapacity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BERTHCAPACITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BERTHCAPACITY = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#berthCapacity"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#berthMaxLength
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BERTHMAXLENGTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BERTHMAXLENGTH = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#berthMaxLength"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#berthName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BERTHNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BERTHNAME = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#berthName"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#berthsAvailable
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BERTHSAVAILABLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BERTHSAVAILABLE = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#berthsAvailable"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#boatLength
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BOATLENGTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BOATLENGTH = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#boatLength"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#boatName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BOATNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BOATNAME = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#boatName"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#color
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COLOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COLOR = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#color"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#engineSize
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGINESIZE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGINESIZE = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#engineSize"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#hasBoat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASBOAT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASBOAT = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#hasBoat"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#hasEngine
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASENGINE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASENGINE = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#hasEngine"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#hasSails
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSAILS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSAILS = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#hasSails"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#havenName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAVENNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAVENNAME = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#havenName"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#providerName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROVIDERNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROVIDERNAME = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#providerName"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#requiresCrew
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property REQUIRESCREW.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_REQUIRESCREW = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#requiresCrew"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#routeName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ROUTENAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ROUTENAME = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#routeName"));

    /* ***************************************************
     * Data Property http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#sleepingSpaces
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SLEEPINGSPACES.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SLEEPINGSPACES = factory.getOWLDataProperty(IRI.create("http://www.co7516coursework1.com/jl571/OntologyJl571.rdf#sleepingSpaces"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
