package uk.ac.le.cs.CO7216.impl;

import uk.ac.le.cs.CO7216.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultStudent <br>
 * @version generated on Tue Mar 15 14:27:49 GMT 2016 by admin
 */
public class DefaultStudent extends WrappedIndividualImpl implements Student {

    public DefaultStudent(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.cs.le.ac.uk/rdf#hasFriend
     */
     
    public Collection<? extends Person> getHasFriend() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASFRIEND,
                                               DefaultPerson.class);
    }

    public boolean hasHasFriend() {
	   return !getHasFriend().isEmpty();
    }

    public void addHasFriend(Person newHasFriend) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASFRIEND,
                                       newHasFriend);
    }

    public void removeHasFriend(Person oldHasFriend) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASFRIEND,
                                          oldHasFriend);
    }


    /* ***************************************************
     * Object Property http://www.cs.le.ac.uk/rdf#knows
     */
     
    public Collection<? extends Person> getKnows() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_KNOWS,
                                               DefaultPerson.class);
    }

    public boolean hasKnows() {
	   return !getKnows().isEmpty();
    }

    public void addKnows(Person newKnows) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_KNOWS,
                                       newKnows);
    }

    public void removeKnows(Person oldKnows) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_KNOWS,
                                          oldKnows);
    }


    /* ***************************************************
     * Object Property http://www.cs.le.ac.uk/rdf#study
     */
     
    public Collection<? extends Module> getStudy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_STUDY,
                                               DefaultModule.class);
    }

    public boolean hasStudy() {
	   return !getStudy().isEmpty();
    }

    public void addStudy(Module newStudy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_STUDY,
                                       newStudy);
    }

    public void removeStudy(Module oldStudy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_STUDY,
                                          oldStudy);
    }


    /* ***************************************************
     * Data Property http://www.cs.le.ac.uk/rdf#has_age
     */
     
    public Collection<? extends Integer> getHas_age() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_AGE, Integer.class);
    }

    public boolean hasHas_age() {
		return !getHas_age().isEmpty();
    }

    public void addHas_age(Integer newHas_age) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_AGE, newHas_age);
    }

    public void removeHas_age(Integer oldHas_age) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_AGE, oldHas_age);
    }


    /* ***************************************************
     * Data Property http://www.cs.le.ac.uk/rdf#has_email
     */
     
    public Collection<? extends String> getHas_email() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_EMAIL, String.class);
    }

    public boolean hasHas_email() {
		return !getHas_email().isEmpty();
    }

    public void addHas_email(String newHas_email) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_EMAIL, newHas_email);
    }

    public void removeHas_email(String oldHas_email) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_EMAIL, oldHas_email);
    }


    /* ***************************************************
     * Data Property http://www.cs.le.ac.uk/rdf#has_full_name
     */
     
    public Collection<? extends String> getHas_full_name() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FULL_NAME, String.class);
    }

    public boolean hasHas_full_name() {
		return !getHas_full_name().isEmpty();
    }

    public void addHas_full_name(String newHas_full_name) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FULL_NAME, newHas_full_name);
    }

    public void removeHas_full_name(String oldHas_full_name) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FULL_NAME, oldHas_full_name);
    }


}
