package uk.ac.le.cs.CO7216.impl;

import uk.ac.le.cs.CO7216.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultModule <br>
 * @version generated on Tue Mar 15 14:27:49 GMT 2016 by admin
 */
public class DefaultModule extends WrappedIndividualImpl implements Module {

    public DefaultModule(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





}
