package uk.ac.le.cs.CO7216;

import uk.ac.le.cs.CO7216.impl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.CodeGenerationFactory;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.FactoryHelper;
import org.protege.owl.codegeneration.impl.ProtegeJavaMapping;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.protege.owl.codegeneration.inference.SimpleInference;

import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

/**
 * A class that serves as the entry point to the generated code providing access
 * to existing individuals in the ontology and the ability to create new individuals in the ontology.<p>
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: OntFactory<br>
 * @version generated on Tue Mar 15 14:27:49 GMT 2016 by admin
 */
public class OntFactory implements CodeGenerationFactory {
    private OWLOntology ontology;
    private ProtegeJavaMapping javaMapping = new ProtegeJavaMapping();
    private FactoryHelper delegate;
    private CodeGenerationInference inference;

    public OntFactory(OWLOntology ontology) {
	    this(ontology, new SimpleInference(ontology));
    }
    
    public OntFactory(OWLOntology ontology, CodeGenerationInference inference) {
        this.ontology = ontology;
        this.inference = inference;
        javaMapping.initialize(ontology, inference);
        delegate = new FactoryHelper(ontology, inference);
    }

    public OWLOntology getOwlOntology() {
        return ontology;
    }
    
    public void saveOwlOntology() throws OWLOntologyStorageException {
        ontology.getOWLOntologyManager().saveOntology(ontology);
    }
    
    public void flushOwlReasoner() {
        delegate.flushOwlReasoner();
    }
    
    public boolean canAs(WrappedIndividual resource, Class<? extends WrappedIndividual> javaInterface) {
    	return javaMapping.canAs(resource, javaInterface);
    }
    
    public  <X extends WrappedIndividual> X as(WrappedIndividual resource, Class<? extends X> javaInterface) {
    	return javaMapping.as(resource, javaInterface);
    }
    
    public Class<?> getJavaInterfaceFromOwlClass(OWLClass cls) {
        return javaMapping.getJavaInterfaceFromOwlClass(cls);
    }
    
    public OWLClass getOwlClassFromJavaInterface(Class<?> javaInterface) {
	    return javaMapping.getOwlClassFromJavaInterface(javaInterface);
    }
    
    public CodeGenerationInference getInference() {
        return inference;
    }

    /* ***************************************************
     * Class http://www.cs.le.ac.uk/rdf#Lecturer
     */

    {
        javaMapping.add("http://www.cs.le.ac.uk/rdf#Lecturer", Lecturer.class, DefaultLecturer.class);
    }

    /**
     * Creates an instance of type Lecturer.  Modifies the underlying ontology.
     */
    public Lecturer createLecturer(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_LECTURER, DefaultLecturer.class);
    }

    /**
     * Gets an instance of type Lecturer with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Lecturer getLecturer(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_LECTURER, DefaultLecturer.class);
    }

    /**
     * Gets all instances of Lecturer from the ontology.
     */
    public Collection<? extends Lecturer> getAllLecturerInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_LECTURER, DefaultLecturer.class);
    }


    /* ***************************************************
     * Class http://www.cs.le.ac.uk/rdf#Module
     */

    {
        javaMapping.add("http://www.cs.le.ac.uk/rdf#Module", Module.class, DefaultModule.class);
    }

    /**
     * Creates an instance of type Module.  Modifies the underlying ontology.
     */
    public Module createModule(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_MODULE, DefaultModule.class);
    }

    /**
     * Gets an instance of type Module with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Module getModule(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_MODULE, DefaultModule.class);
    }

    /**
     * Gets all instances of Module from the ontology.
     */
    public Collection<? extends Module> getAllModuleInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_MODULE, DefaultModule.class);
    }


    /* ***************************************************
     * Class http://www.cs.le.ac.uk/rdf#Person
     */

    {
        javaMapping.add("http://www.cs.le.ac.uk/rdf#Person", Person.class, DefaultPerson.class);
    }

    /**
     * Creates an instance of type Person.  Modifies the underlying ontology.
     */
    public Person createPerson(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }

    /**
     * Gets an instance of type Person with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Person getPerson(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }

    /**
     * Gets all instances of Person from the ontology.
     */
    public Collection<? extends Person> getAllPersonInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }


    /* ***************************************************
     * Class http://www.cs.le.ac.uk/rdf#Student
     */

    {
        javaMapping.add("http://www.cs.le.ac.uk/rdf#Student", Student.class, DefaultStudent.class);
    }

    /**
     * Creates an instance of type Student.  Modifies the underlying ontology.
     */
    public Student createStudent(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_STUDENT, DefaultStudent.class);
    }

    /**
     * Gets an instance of type Student with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Student getStudent(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_STUDENT, DefaultStudent.class);
    }

    /**
     * Gets all instances of Student from the ontology.
     */
    public Collection<? extends Student> getAllStudentInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_STUDENT, DefaultStudent.class);
    }


}
