package com.boating.cs.impl;

import com.boating.cs.CommercialBoat;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCommercialBoat <br>
 * @version generated on Mon Apr 16 16:18:00 CEST 2018 by fh231
 */
public class DefaultCommercialBoat extends WrappedIndividualImpl implements CommercialBoat {

    public DefaultCommercialBoat(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
